"""前沿主题关键词：粗筛突破性方向（世界模型 / Agent / AI 机器人 / 大模型等）。"""

# 可用 ARXIV_TOPIC_KEYWORDS 覆盖（逗号分隔）
DEFAULT_TOPIC_KEYWORDS = [
    # 世界模型 / 具身
    "world model",
    "world models",
    "latent world",
    "embodied",
    "embodied ai",
    "embodied intelligence",
    "robotics foundation",
    # AI 机器人 / 具身智能
    "robot",
    "robotic",
    "robotics",
    "humanoid",
    "humanoid robot",
    "manipulator",
    "manipulation",
    "dexterous",
    "loco-manipulation",
    "vision-language-action",
    "vision language action",
    "vla",
    "vla model",
    "policy learning",
    "imitation learning",
    "teleoperation",
    "sim-to-real",
    "sim2real",
    "quadruped",
    "mobile manipulator",
    "warehouse robot",
    "service robot",
    # Agent
    "agent",
    "multi-agent",
    "tool use",
    "tool-use",
    "computer use",
    "autonomous agent",
    "agentic",
    # 大模型前沿
    "large language model",
    "foundation model",
    "llm",
    "reasoning model",
    "chain of thought",
    "test-time compute",
    "reinforcement learning from",
    "rlhf",
    "rlvr",
    "post-training",
    "alignment",
    "multimodal",
    "vision-language",
    "vlm",
    # 社会智能 / 类知境
    "social intelligence",
    "theory of mind",
    "theory-of-mind",
    "social mind",
    "social reasoning",
    "human-ai",
    "human-robot",
    "human robot interaction",
    # 突破性表述（弱信号）
    "state-of-the-art",
    "state of the art",
    "breakthrough",
    "surpasses",
    "outperforms gpt",
    "open-ended",
]
